#! /usr/bin/env sh

# Install Nerd Fonts
mkdir -p ~/.local/share/fonts
cd ~/.local/share/fonts
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
unzip JetBrainsMono.zip
mkdir -p JetBrainsMono
mv JetBrains*.ttf JetBrainsMono
rm JetBrains*.zip



