#! /usr/bin/env sh

pkg install xorg mate firefox thunderbird mesa-libs mesa-dri x-clipboard libva-intel-driver drm-kmod xf86-video-intel xf86-video-scfb

# test to see if drivers enabled, and if not, enable them
# grep -qxF 'kld_list="/boot/modules/i915kms.ko"' /etc/rc.conf || echo 'kld_list="/boot/modules/i915kms.ko"' >> /etc/rc.conf

rm /usr/local/etc/X11/xorg.conf.d/driver*
ln -s /home/cameron/.dots/driver-scfb.conf /usr/local/etc/X11/xorg.conf.d

powersaving="# Try to skip unnecessary mode sets at boot time
compat.linuxkpi.i915_fastboot=1

# Enable power-saving display C-states (0=disable; 1=up to DC5; 2=up to DC6)
compat.linuxkpi.i915_enable_dc=2

# Disable display power wells when possible (0=power wells always on, 1=power wells disabled when possible)
compat.linuxkpi.i915_disable_power_well=1

# Enable frame buffer compression for power savings
compat.linuxkpi.i915_enable_fbc=1"

grep -qxF $powersaving /boot/loader.conf || echo $powersaving >> /boot/loader.conf 
