#!/usr/bin/env sh

dir=~/.dots
files="doom.d profile tmux.conf vimrc zshrc"

cd $dir

for file in $files; do
  rm -r ~/.$file
  echo "Creating symlink to $file in home directory."
  ln -s $dir/$file ~/.$file
done

xiles=$(ls ~/.dots/config)

for file in $xiles; do
  rm -r ~/.config/$file
  echo "Creating symlink to $file in home directory."
  ln -s $dir/config/$file ~/.config/$file
done

mkdir -p ~/.local/bin
rm ~/.local/bin/reload_dots
echo "Updating reload_dots script"
ln -s $dir/install.d/reload_dots ~/.local/bin/reload_dots
